export const laguageCodeList=[
    {name:"Arabic",code:"ar"},
    // {name:"Assamese",code:"as"},
    {name:"Bengali",code:"bn"},
    // {name:"Bhojpuri",code:"bho"},
    {name:"Chinese ",code:"zh-CN"},
    {name:"French",code:"fr"},
    {name:"German",code:"de"},
    {name:"Greek",code:"el"},
    {name:"Gujarati",code:"gu"},
    {name:"Hindi",code:"hi"},
    {name:"Italian",code:"it"},
    {name:"Japanese",code:"ja"},
    {name:"Kannada",code:"kn"},
    {name:"Korean",code:"ko"},
    {name:"Latin",code:"la"},
    {name:"Malayalam",code:"ml"},
    {name:"Marathi",code:"mr"},
    {name:"Nepali",code:"ne"},
    {name:"Portuguese ",code:"pt"},
    {name:"Russian",code:"ru"},
    // {name:"Sanskrit	",code:"sa"},
    {name:"Tamil",code:"ta"},
    {name:"Telugu",code:"te"},
    {name:"Urdu",code:"ur"}
]